## Numpy

In [2]:
import numpy as np
test_array = np.array([1,4,5,8],float)    #numpy는 하나의 daya type만 배열에 넣을 수 있음
print(test_array)
test_array.dtype

[1. 4. 5. 8.]


dtype('float64')

#### Array의 Rank(dimension) 
#### 0 : scalar 
#### 1 : vector
#### 2 : matrix 
#### 3 : 3-tensor
#### n : n-tensor

In [3]:
np.array([1,2,3,4]).shape

(4,)

In [4]:
np.array([[1,2,3,4],[5,6,7,8]]).shape

(2, 4)

#### byte 확인

In [5]:
np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float32).nbytes

32

#### shape 변경(element 개수는 동일)

In [6]:
np.array([[1,2,3,4],[5,6,7,8]]).reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.array([[1,2,3,4],[5,6,7,8]]).reshape(-1,2)    # size 기반으로 row 개수 선정

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
np.array([[1,2,3,4],[5,6,7,8]]).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
np.array([[1,2,3,4],[5,6,7,8]]).reshape(2,-1,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### slicing for np array

In [14]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
print(a[:,2:])    #전체 ROW의 2열 이상
a[1,1:3]    #1 Row의 1열~2열
a[1:3]   #1row~3row의 전체

array([[ 6,  7,  8,  9, 10]])

In [15]:
a[:,::2]#start end step

array([[ 1,  3,  5],
       [ 6,  8, 10]])

#### np.arange, zeros, ones, empty

In [16]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [21]:
np.ones(shape=(2,5),dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [26]:
a = np.empty((3,5), dtype=np.int8)   #다른 프로그램의 값이 남아있음
a

array([[ 80, -78, -29,  96, 127],
       [  1,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=int8)

In [27]:
np.ones_like(a)    #a모양

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

#### 단위행렬 i, eye

In [28]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(3,5,k=2)   #k는 시작지점

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.random sampling  
#### 데이터 분포에 따른 sampling으로 array를 생성

In [33]:
np.random.uniform(0,1,10).reshape(2,5)    #균등분포

array([[0.6507977 , 0.92950921, 0.30147774, 0.05361099, 0.3566996 ],
       [0.59762265, 0.22795394, 0.39026177, 0.88579978, 0.12285438]])

In [35]:
np.random.exponential(scale=2,size=100)

array([2.98520798, 3.27368971, 6.42633306, 3.28583723, 0.41082333,
       0.42799649, 3.0667913 , 4.00261147, 3.71415404, 2.8180502 ,
       0.58169823, 0.42123501, 1.52004028, 0.35421745, 3.25838369,
       1.69771522, 0.08821304, 3.93761306, 3.91347177, 1.07677066,
       1.32440096, 2.81533747, 1.30215106, 1.35676226, 1.37057308,
       1.43727435, 1.62174451, 1.84240458, 4.48047533, 0.71700115,
       8.35552734, 0.47550319, 2.77999601, 2.34029263, 1.1156106 ,
       0.03554498, 1.20669981, 1.81363726, 1.96959988, 0.26800342,
       5.62629905, 4.40193482, 2.5623095 , 2.87077916, 0.43502338,
       1.17540743, 0.09132956, 0.58319932, 1.39165361, 6.42655246,
       4.56587213, 0.7423727 , 2.06333788, 0.94297821, 0.2614908 ,
       3.93624846, 0.9650495 , 1.40605077, 1.12442349, 0.6275152 ,
       4.43891986, 4.52310747, 0.50994408, 0.24639868, 0.51511119,
       4.09597817, 2.85681738, 5.67386463, 2.67354603, 7.59400319,
       2.09060545, 2.37557507, 2.25468548, 9.2547809 , 0.79220

#### 그 외 함수

In [39]:
a = np.arange(10)
a.sum()

45

In [40]:
a.std()

2.8722813232690143

In [41]:
a.mean()

4.5

#### axis : 모든 operation을 실행할 때 기준이 되는 dimension 축

In [43]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
test_array.sum(axis=1),test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [46]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [47]:
third_order_tensor.sum(axis=0)    #z축

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [48]:
third_order_tensor.sum(axis=1)    #y축

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [49]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))    #vertical

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [54]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
a = np.array([[1,2],[3,4]])
b = np.array([[5],[6]])
np.concatenate((a,b),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [63]:
a = [[1,2,3]]
b = [[2,3,4]]
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 2, 3, 4]])

#### 사칙연산(shape이 동일할 때)

In [66]:
test_a = np.array([[1,2,3],[4,5,6]],float)
test_a+test_a    #matrix+matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [67]:
test_a-test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
test_a*test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

#### boolean 연산

In [3]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
test_a > test_b

array([False,  True, False])

In [4]:
np.any(test_a>2)

True

In [5]:
np.all(test_a>2)

False

In [6]:
test_a==test_b

array([False, False, False])

In [7]:
(test_a>test_b).any()

True

In [8]:
np.logical_and(test_a>0,test_a<2)

array([ True, False, False])

In [9]:
np.logical_or(test_a>0,test_a<2)

array([ True,  True,  True])

In [10]:
np.where(test_a>1,100,-1)    #condition, true, false

array([ -1, 100,  -1])

In [11]:
a = np.array([1,np.NaN, np.Inf],float)
np.isnan(a)

array([False,  True, False])

In [12]:
np.isfinite(a)

array([ True, False, False])

In [15]:
np.argmax(test_a)

1

In [17]:
np.argmin(test_a)

2

In [18]:
test_array = np.array([1,4,0,3,7,8,5,9,2])
test_array[test_array>3]

array([4, 7, 8, 5, 9])

In [19]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,1,2],int)    #반드시 int로 선언
a[b]

array([2., 2., 4., 6.])

In [25]:
a = np.array([[1,2,3,4,5],[1,2,5,6,2]])
np.savetxt('first_data.csv',a,fmt="%.2e",delimiter=",")